-- ==========================================
-- 1. SETUP & UTILITIES
-- ==========================================

-- Enable PostGIS if you want to store geometry (Optional, using JSONB for now as requested)
-- create extension if not exists postgis;

-- ==========================================
-- 2. PUBLIC PROFILES (Base User Table)
-- ==========================================
create table if not exists public.users (
  id uuid references auth.users on delete cascade primary key,
  role text check (role in ('farmer', 'sugar_factory')),
  full_name text,
  mobile text,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.users enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on public.users for select using (true);
create policy "Users can update own profile." on public.users for update using (auth.uid() = id);

-- ==========================================
-- 3. FARMERS (Specific Attributes)
-- ==========================================
create table if not exists public.farmers (
  id uuid references public.users(id) on delete cascade primary key,
  address text,
  linked_factory_id uuid, -- Link to a factory (future use)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.farmers enable row level security;

-- Policies
create policy "Farmers can manage own details" on public.farmers for all using (auth.uid() = id);

-- ==========================================
-- 4. SUGAR FACTORIES (Specific Attributes)
-- ==========================================
create table if not exists public.sugar_factories (
  id uuid references public.users(id) on delete cascade primary key,
  factory_name text,
  registration_number text,
  district text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.sugar_factories enable row level security;

-- Policies
create policy "Factories can manage own details" on public.sugar_factories for all using (auth.uid() = id);

-- ==========================================
-- 5. FIELDS (The Physical Land)
-- ==========================================
create table if not exists public.fields (
  id bigint generated by default as identity primary key,
  farmer_id uuid references public.farmers(id) on delete cascade not null,
  name text not null,
  area_size decimal, -- In Acres or Hectares
  coordinates jsonb, -- Stores array of {lat, lng}
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.fields enable row level security;

-- Policies
create policy "Farmers can CRUD own fields" on public.fields 
  for all using (auth.uid() = farmer_id);

-- ==========================================
-- 6. FIELD DETAILS (The Crop Configuration)
-- ==========================================
create table if not exists public.field_details (
  id bigint generated by default as identity primary key,
  field_id bigint references public.fields(id) on delete cascade not null,
  
  -- Attributes
  crop_name text default 'Sugarcane',
  taluka text check (taluka in ('Akole', 'Sangamner', 'Kopargaon', 'Rahata', 'Shrirampur', 'Nevasa', 'Shevgaon', 'Pathardi', 'Jamkhed', 'Karjat', 'Shrigonda', 'Parner', 'Ahmednagar', 'Rahuri')),
  season text check (season in ('Suru', 'Pre-seasonal', 'Adsali')),
  variety text check (variety in ('CoM 0265', 'Co 86032', 'Co 92005', 'VSI 434')),
  soil_type text check (soil_type in ('Black Cotton', 'Clay Loam', 'Sandy Loam', 'Medium Black')),
  irrigation_method text check (irrigation_method in ('Drip', 'Flood', 'Rainfed')),
  planting_date date,
  is_active boolean default true,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.field_details enable row level security;

-- Policies (Indirect access via field ownership)
create policy "Farmers can CRUD details of their fields" on public.field_details 
for all using (
  exists (
    select 1 from public.fields 
    where public.fields.id = public.field_details.field_id 
    and public.fields.farmer_id = auth.uid()
  )
);

-- ==========================================
-- 7. AUTOMATION (Triggers)
-- ==========================================
-- Function to handle new user signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  -- 1. Insert into public.users
  insert into public.users (id, role, full_name, mobile, email)
  values (
    new.id, 
    new.raw_user_meta_data->>'role', 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'mobile',
    new.email
  );

  -- 2. Insert into specific role table
  if (new.raw_user_meta_data->>'role' = 'farmer') then
      insert into public.farmers (id) values (new.id);
  elsif (new.raw_user_meta_data->>'role' = 'sugar_factory') then
      insert into public.sugar_factories (id) values (new.id);
  end if;

  return new;
end;
$$ language plpgsql security definer;

-- Trigger checks every time a User is created in Auth
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
